gui:
  border: rounded
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#82aaff"
      - bold
    inactiveBorderColor:
      - "#636da6"
    searchingActiveBorderColor:
      - "#86e1fc"
      - bold
    optionsTextColor:
      - "#82aaff"
    selectedLineBgColor:
      - "#2f334d"
    inactiveViewSelectedLineBgColor:
      - "#2f334d"
    cherryPickedCommitFgColor:
      - "#82aaff"
    cherryPickedCommitBgColor:
      - "#c099ff"
    markedBaseCommitFgColor:
      - "#82aaff"
    markedBaseCommitBgColor:
      - "#ffc777"
    unstagedChangesColor:
      - "#ff757f"
    defaultFgColor:
      - "#c8d3f5"
