# set leader r to resource tmux conf file
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# set control space as the leader key
unbind-key C-b
set-option -g prefix C-s
bind-key C-s send-prefix

#vim motions to move between panes
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# resize panes with prefix + Ctrl + vim motion keys
unbind-key -q C-Left
unbind-key -q C-Down
unbind-key -q C-Up
unbind-key -q C-Right
bind-key -r C-h resize-pane -L 10
bind-key -r C-j resize-pane -D 10
bind-key -r C-k resize-pane -U 10
bind-key -r C-l resize-pane -R 10

# allow mouse
set -g mouse on

# first tmux window starts at 1
set -g base-index 1

set-option -g status-position top

# Load the Tokyo Night Moon theme for tmux colors and status styling.
source-file ~/.config/tmux/tokyonight_moon.tmux
